In [ ]:
'''I learned and practiced NumPy for Data Science, focusing on arrays, indexing, slicing, mathematical operations, aggregation functions, Boolean filtering, 2D arrays, reshaping, and basic statistical analysis.

I also built a Student Performance Analyzer using NumPy to calculate student averages, subject averages, highest and lowest marks, overall class performance, student totals, passing/failed students, and the highest-performing subject.'''

In [2]:
import numpy as np

In [3]:
np.array([1,2])

array([1, 2])

In [4]:
names = np.array(['ali','usman','hadier'])
print(names)

['ali' 'usman' 'hadier']


In [6]:
info = np.array([123,'ali',890000.2,True])
print(info)

['123' 'ali' '890000.2' 'True']


In [14]:
# One Dimension Array
sal = np.array([78900,100000,50000,34500,2990999])
print(sal)
np.ndim(sal)

[  78900  100000   50000   34500 2990999]


1

In [20]:
# Two Dimension Array
dep = np.array([['AI'],['Visual Studies']])
print(dep)
np.ndim(dep)

[['AI']
 ['Visual Studies']]


2

In [22]:
# Three Dimension Array
color = np.array([[['black','red'],['light brown','light green'],['pink','white']]])
print(color)
np.ndim(color)

[[['black' 'red']
  ['light brown' 'light green']
  ['pink' 'white']]]


3

In [26]:
# Shape
age = np.array([56,90,23,16,7,89,56,63,32,24,6])
age.shape
np.shape(age)

(11,)

In [27]:
# Size
age.size

11

In [30]:
# Data Type
cars = np.array([123,'honda',True,5678.90])
cars.dtype

age.dtype

product_price = np.array([78.9,78.45,66.21])
product_price.dtype

dtype('float64')

In [32]:
# Creating Numpy Arrays
np.array([34,56,78,90])

array([34, 56, 78, 90])

In [33]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [36]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
np.arange(1,8,2)

array([1, 3, 5, 7])

In [46]:
np.linspace(0,100,6) # Use for evenly Spacing

array([  0.,  20.,  40.,  60.,  80., 100.])

In [50]:
np.arange(5,101,5)

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

In [57]:
# Indexing
marks = np.array([34,78,45,89,98,45,49,76])
print(marks[0])
print(marks[-1])
print(marks[1])
print(marks[-2])

34
76
78
49


In [59]:
# Changing Number using Indexing
marks[-4] = 96
print(marks)

[34 78 45 89 96 45 49 76]


In [65]:
# Slicing
marks[1:2]
marks[-5:]
marks[3:5]
marks[:-3]
marks[2:-2]

array([45, 89, 96, 45])

In [85]:
# Aggregation Functions

print(marks.sum())
print(marks.min())
print(marks.max())
print(marks.mean())
print(marks.std())

print(marks.argmax())
print(marks.argmin())

512
34
96
64.0
21.89748844045819
4
0


In [75]:
# Mathematical Operations
sales = np.array([123891,90352,100000,453600,980000])
print(sales + 1000)
print(sales - 1000)
print(sales * 2)
print(sales / 2)



[124891  91352 101000 454600 981000]
[122891  89352  99000 452600 979000]
[ 247782  180704  200000  907200 1960000]
[ 61945.5  45176.   50000.  226800.  490000. ]


In [80]:
salary = np.array([30000, 45000, 50000, 60000])
print('10 % of Sal: ', sal * 0.1)
print('New Sal of Emp: ',sal + (sal*0.1))

10 % of Sal:  [  7890.   10000.    5000.    3450.  299099.9]
New Sal of Emp:  [  86790.   110000.    55000.    37950.  3290098.9]


In [84]:
# Array to Array Operations
revenue = np.array([10000, 15000, 20000, 12000])
cost = np.array([6000, 8000, 12000, 7000])

profit = revenue - cost
print(profit)

profit_margin = profit / revenue * 100
print(profit_margin)

[4000 7000 8000 5000]
[40.         46.66666667 40.         41.66666667]


In [91]:
# Boolean Filtering
shoes_prices = np.array([2000,5500,7890,2314,1034])
shoes_prices[shoes_prices > 2000]


array([5500, 7890, 2314])

In [92]:
shoes_prices < 6500

array([ True,  True, False,  True,  True])

In [93]:
shoes_prices[shoes_prices < 6500]

array([2000, 5500, 2314, 1034])

In [94]:
shoes_prices[shoes_prices >= 2314]

array([5500, 7890, 2314])

In [99]:
shoes_prices[(shoes_prices >= 1000) & (shoes_prices <= 5500)]

array([2000, 5500, 2314, 1034])

In [106]:
# 2D Array Challenge
std_marks = np.array([[80,75,90],[65,88,92],[70,85,78]])
print(std_marks)

print('Highest Mark of Student: ',np.max(std_marks))
print('Average Subject Marks: ',np.mean(std_marks,axis=0)) # Average of column wise
print('Average Student Marks: ',np.mean(std_marks,axis=1)) # Average of row wise
high_index = np.argmax(std_marks)
print('Highest Marks Index: ',high_index + 1 )

[[80 75 90]
 [65 88 92]
 [70 85 78]]
Highest Mark of Student:  92
Average Subject Marks:  [71.66666667 82.66666667 86.66666667]
Average Student Marks:  [81.66666667 81.66666667 77.66666667]
Highest Marks Index:  6


In [111]:
# Random Numbers
np.random.randint(1,100,87)

array([36, 20, 96, 59, 16, 78, 64, 81, 25, 30, 99, 28,  3, 66,  7, 24, 90,
       48, 87, 53, 25, 77, 77, 55,  1, 79, 77,  6, 39,  5, 34, 66, 45, 53,
       52, 24, 17, 54,  5, 67, 77, 25,  3,  8, 73, 92, 16, 84, 63, 64, 25,
        5, 53, 18,  8, 22, 43, 55, 72, 64, 59, 56, 20, 87, 20, 57, 29, 24,
       30, 99, 34,  5,  4, 44, 79, 80, 51, 92, 76, 26, 89, 82, 41, 64, 41,
       89, 15])

In [114]:
np.random.randint(2,9)

4

In [117]:
temp = np.random.randint(1,100,30)
print("Temperature in 30 Days: ", temp)

print("Average Temp: ",np.mean(temp))
print("Highest Temp: ",np.max(temp))
print("Lowest Temp: ",np.min(temp))
temp[temp >= 50]

Temperature in 30 Days:  [78 56 53 81 89 86 21 76 18 71 23 82 84 48 61 73 17  6 61 10 54  1 48 71
 35 29 53 29 60 78]
Average Temp:  51.733333333333334
Highest Temp:  89
Lowest Temp:  1


array([78, 56, 53, 81, 89, 86, 76, 71, 82, 84, 61, 73, 61, 54, 71, 53, 60,
       78])

In [131]:
# Mini Project — Student Performance Analyzer
import numpy as np

marks = np.array([
    [85, 78, 90, 88],
    [72, 80, 75, 79],
    [91, 88, 95, 92],
    [65, 70, 68, 72],
    [88, 92, 85, 90],
    [76, 82, 80, 78],
    [95, 90, 94, 96],
    [60, 65, 30, 68],
    [84, 79, 88, 85],
    [73, 75, 77, 80]
])

subjects = ["Python", "SQL", "Statistics", "Machine Learning"]

# 1. Shape
print("Shape:", marks.shape)

# 2. Average marks of every student
student_average = np.mean(marks, axis=1)
print("Average marks of every student:", student_average)

# 3. Average marks of every subject
subject_average = np.mean(marks, axis=0)
print("Average marks of every subject:", subject_average)

# 4. Highest mark in every subject
print("Highest marks of every subject:", np.max(marks, axis=0))

# 5. Lowest mark in every subject
print("Lowest marks of every subject:", np.min(marks, axis=0))

# 6. Overall class average
print("Overall Class Average:", np.mean(marks))

# 7. Student with highest total marks
student_totals = np.sum(marks, axis=1)
highest_student = np.argmax(student_totals)

print("Student with Highest Total Marks:",
      highest_student + 1)

# 8. Students with average >= 80
high_performers = np.where(student_average >= 80)[0] + 1
print("Students with Average >= 80:", high_performers)

# 9. Students with average < 70
low_performers = np.where(student_average < 70)[0] + 1
print("Students with Average < 70:", low_performers)

# 10. Students who passed
passed = student_average >= 50
print("Number of Students Passed:", np.sum(passed))

# 11. Students who failed any subject
failed_students = np.where(np.any(marks < 50, axis=1))[0] + 1
print("Students who Failed Any Subject:", failed_students)

# 12. Highest performing subject
highest_subject = np.argmax(subject_average)

print("Highest Performing Subject:",
      subjects[highest_subject])


Shape: (10, 4)
Average marks of every student: [85.25 76.5  91.5  68.75 88.75 79.   93.75 55.75 84.   76.25]
Average marks of every subject: [78.9 79.9 78.2 82.8]
Highest marks of every subject: [95 92 95 96]
Lowest marks of every subject: [60 65 30 68]
Overall Class Average: 79.95
Student with Highest Total Marks: 7
Students with Average >= 80: [1 3 5 7 9]
Students with Average < 70: [4 8]
Number of Students Passed: 10
Students who Failed Any Subject: [8]
Highest Performing Subject: Machine Learning
